name: Build Jekyll site

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll
        run: |
          gem install bundler jekyll

      - name: Build site
        run: |
          bundle exec jekyll build || jekyll build
